# SPDX-FileCopyrightText: 2025 Nordeck IT + Consulting GmbH
#
# SPDX-License-Identifier: CC0-1.0

# Use single quotes instead of double quotes.
# (this will not affect JSX)
singleQuote: true

plugins: ['prettier-plugin-organize-imports']
